### ISSUE TITLE
Input data structure for molecule

### ISSUE THREAD

**Issue by EasternCaveMan** [kalininalab/DataSAIL#10]
Hi Roman,

I've noticed that DataSAIL doesn't currently accept InChI as input for molecules. However, I'm wondering if I could convert the InChI to ECFP and then provide it as input to DataSAIL? It seems that converting InChI to SMILES is quite risky, as indicated in these discussions:
https://github.com/rdkit/rdkit/issues/542
https://sourceforge.net/p/rdkit/mailman/message/36696861/

It would significantly enhance usability if DataSAIL could also accept ECFP as input for molecules, making it more universal.

**Comment by Old-Shatterhand** [comment]
Yes, fingerprint input may be an idea. What's also possible is to calculate the similarity-matrix on your own and input that with the --e-sim argument as in this [example](https://datasail.readthedocs.io/en/latest/examples/bace.html).

**Comment by Old-Shatterhand** [comment]
This has been solved with commit [35954ce](https://github.com/kalininalab/DataSAIL/commit/35954ce0fcfa2989cab791ddceabcd0be9f3f705).
