### ISSUE TITLE
DataSAIL not available for Mac Apple Silicon M1 chip

### ISSUE THREAD

**Issue by tanyamalkani** [kalininalab/DataSAIL#7]
I have difficulty in installing DataSAIL on my MacBook with Apple M1 chip (AArch64/osx-arm64 architecture).

Currently, have used a workaround by `conda config --env --set subdir osx-64` and followed the instructions in the documentation as usual. The installation was a success, however, not sure if the translation would work correctly as it might not be optimized for the newer M1 architecture.

Requesting to please make it available for arm64

Thank you

**Comment by Old-Shatterhand** [comment]
Hey @tanyamalkani,

I modified the build-and-upload pipeline to provide `osx-arm64` and `win-64` builds of DataSAIL. Please check if this solves your issue and let me know.

Best, Roman
